### ISSUE TITLE
aarch64 is not published

### ISSUE THREAD

**Issue by thebestnom** [conda-forge/typing_extensions-feedstock#11]
For some reason the aarch64 build is not uploaded and I can't find it on the azure
cc @conda-forge/core

**Comment by beckermr** [comment]
Probably a drone issue. A maintainer needs to push a commit to master. cc @conda-forge/typing_extensions

**Comment by thebestnom** [comment]
@beckermr just open a PR and bump build and Ill ask you to merge, is that OK?

**Comment by beckermr** [comment]
+1

**Comment by thebestnom** [comment]
@beckermr it did't help, I thinking about changing aarch64 and ppc to work agains azure, is that ok?

**Comment by beckermr** [comment]
That would be fine. Those builds are emulated and you only get 6 hours of emulated build time. They may not complete depending on the package.

**Comment by thebestnom** [comment]
Thannks!
